global:
  marketplace-ami: false
  owner: somckitk@amazon.com
  qsname: quickstart-sap-netweaver-abap
  regions:
    - eu-west-1
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
  reporting: true
tests:
  master:
    template_file: sap-netweaver-abap-master.template
    parameter_input: sap-netweaver-abap-master.json
