global:
  marketplace-ami: false
  owner: somckitk@amazon.com
  qsname: quickstart-sap-netweaver-abap
  regions:
    - eu-central-1
    - eu-west-1
    - us-east-1
    - us-east-2
    - us-west-1
    - us-west-2
    - ap-northeast-1
    - ap-northeast-2
    - ap-south-1
    - ap-southeast-1
    - ap-southeast-2
  reporting: true
tests:
  scenario-1:
    template_file: sap-netweaver-abap-master.template
    parameter_input: sap-netweaver-abap-master.json
